"""Parser for compile_commands.json to extract per-file compile flags."""

import json
import re
import shlex
from pathlib import Path
from typing import Any


class CompileCommandsDB:
    """
    Parses compile_commands.json and provides per-file compile flags.

    compile_commands.json is generated by build systems like CMake with
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON, Bear, or other tools. It contains
    the exact compile flags used for each source file.
    """

    def __init__(self, compile_commands_path: str | Path | None = None):
        """
        Initialize the compile commands database.

        Args:
            compile_commands_path: Path to compile_commands.json file.
                                   If None, no per-file flags are available.
        """
        self._commands: dict[str, list[str]] = {}
        self._directory_map: dict[str, str] = {}
        self._aggregator_cache: dict[str, str | None] = {}

        if compile_commands_path:
            self._load(compile_commands_path)

    def _load(self, path: str | Path) -> None:
        """Load and parse the compile_commands.json file."""
        path = Path(path)
        if not path.exists():
            raise FileNotFoundError(f"compile_commands.json not found: {path}")

        with open(path, encoding="utf-8") as f:
            data = json.load(f)

        for entry in data:
            self._parse_entry(entry)

    def _parse_entry(self, entry: dict[str, Any]) -> None:
        """Parse a single compile command entry."""
        file_path = entry.get("file", "")
        directory = entry.get("directory", "")

        # Normalize the file path
        if not Path(file_path).is_absolute():
            file_path = str(Path(directory) / file_path)
        file_path = str(Path(file_path).resolve())

        # Extract compile flags
        if "arguments" in entry:
            args = entry["arguments"]
        elif "command" in entry:
            args = shlex.split(entry["command"])
        else:
            return

        # Filter out the compiler and source file, keep relevant flags
        flags = self._extract_flags(args, file_path, directory)

        self._commands[file_path] = flags
        self._directory_map[file_path] = directory

    # Flags to drop: codegen/optimisation/warning flags irrelevant to parsing,
    # plus flags that confuse libclang.
    _SKIP_FLAGS = frozenset((
        "-c", "-g", "-O0", "-O1", "-O2", "-O3", "-Os", "-Oz", "-Og",
        "-fvisibility-inlines-hidden", "-fdiagnostics-color",
        "-fsized-deallocation",
    ))
    _SKIP_PREFIXES = (
        "-O",           # optimisation
        "-W",           # warnings
        "-f",           # codegen feature flags (-flto, -fPIC, …)
        "-g",           # debug info variants (-gdwarf-4 etc.)
        "-march", "-mtune", "-mcpu",  # arch tuning
        "-save-temps",  # codegen artefact
    )

    def _extract_flags(self, args: list[str], source_file: str, directory: str = "") -> list[str]:
        """Extract compiler flags relevant to parsing from a compile command.

        Uses a denylist: drops compiler executable, source/output files,
        dependency-generation flags, and codegen/warning/optimisation flags
        that don't affect how libclang resolves headers or parses the AST.
        Everything else is kept.
        """
        flags: list[str] = []
        skip_next = False
        source_name = Path(source_file).name

        for i, arg in enumerate(args):
            if skip_next:
                skip_next = False
                continue

            # Skip compiler executable (first argument)
            if i == 0 and ("/" in arg or arg.startswith("cc") or
                          arg.endswith(("cc", "c++", "gcc", "g++",
                                        "clang", "clang++", "clang++-18"))):
                continue

            # Skip source file. compile_commands.json may store the source
            # as the absolute path, the bare basename, or — like musl — a
            # path relative to ``directory``. Normalise relative args before
            # comparison so the latter case isn't passed through to libclang
            # as a stray positional argument.
            if arg == source_file or arg == source_name:
                continue
            if (
                directory
                and arg.endswith(source_name)
                and not Path(arg).is_absolute()
            ):
                try:
                    if str(Path(directory, arg).resolve()) == source_file:
                        continue
                except (OSError, ValueError):
                    pass

            # Skip output file
            if arg == "-o":
                skip_next = True
                continue
            if arg.startswith("-o"):
                continue

            # Skip dependency generation flags
            if arg.startswith("-M"):
                if arg in ("-MF", "-MT", "-MQ"):
                    skip_next = True
                continue

            # Skip codegen / warning / optimisation flags
            if arg in self._SKIP_FLAGS:
                continue
            if any(arg.startswith(p) for p in self._SKIP_PREFIXES):
                continue

            # Resolve relative include paths against directory
            if directory and arg.startswith(("-I", "-isystem", "-iquote")):
                for prefix in ("-isystem", "-iquote", "-I"):
                    if arg.startswith(prefix):
                        inc_path = arg[len(prefix):]
                        if inc_path and not Path(inc_path).is_absolute():
                            arg = f"{prefix}{Path(directory) / inc_path}"
                        break

            flags.append(arg)

        return flags

    def get_compile_flags(self, file_path: str | Path) -> list[str]:
        """
        Get compile flags for a specific source file.

        Lookup order: exact path → basename match (handles docker/host
        path discrepancies) → amalgamation aggregator (a .c file in the
        same directory that ``#include``s this one, e.g. freetype's
        ``src/bdf/bdf.c`` includes ``bdfdrivr.c``).

        Args:
            file_path: Path to the source file

        Returns:
            List of compiler flags for this file, or empty list if not found
        """
        resolved = str(Path(file_path).resolve())
        result = self._commands.get(resolved)
        if result is not None:
            return result
        basename = Path(resolved).name
        for key, flags in self._commands.items():
            if Path(key).name == basename:
                return flags
        agg = self.find_aggregator(file_path)
        if agg:
            return self._commands.get(agg, [])
        return []

    def find_aggregator(self, file_path: str | Path) -> str | None:
        """Find a same-directory ``.c`` file that ``#include``s this one.

        Some projects use an amalgamation pattern where a single
        translation unit textually includes several ``.c`` files (e.g.
        freetype's ``src/bdf/bdf.c`` does ``#include "bdfdrivr.c"``).
        Such included files do not appear in ``compile_commands.json``.
        This helper returns the aggregator's absolute path so callers
        can fall back to its compile flags. Results are cached.
        """
        resolved = str(Path(file_path).resolve())
        if resolved in self._aggregator_cache:
            return self._aggregator_cache[resolved]
        if resolved in self._commands:
            self._aggregator_cache[resolved] = None
            return None

        file_dir = str(Path(resolved).parent)
        file_name = Path(resolved).name
        pattern = re.compile(
            rf'^\s*#\s*include\s+["<][^">]*\b{re.escape(file_name)}[">]',
            re.MULTILINE,
        )

        for candidate in self._commands:
            if str(Path(candidate).parent) != file_dir:
                continue
            try:
                with open(candidate, encoding="utf-8", errors="replace") as f:
                    content = f.read()
            except OSError:
                continue
            if pattern.search(content):
                self._aggregator_cache[resolved] = candidate
                return candidate

        self._aggregator_cache[resolved] = None
        return None

    def get_directory(self, file_path: str | Path) -> str | None:
        """
        Get the working directory for compiling a specific file.

        Args:
            file_path: Path to the source file

        Returns:
            The directory from compile_commands.json, or None if not found
        """
        file_path = str(Path(file_path).resolve())
        return self._directory_map.get(file_path)

    def has_file(self, file_path: str | Path) -> bool:
        """Check if we have compile flags for a specific file."""
        file_path = str(Path(file_path).resolve())
        return file_path in self._commands

    def get_all_files(self) -> list[str]:
        """Get list of all files in the compile commands database."""
        return list(self._commands.keys())

    def __len__(self) -> int:
        """Return number of files in the database."""
        return len(self._commands)

    def __bool__(self) -> bool:
        """Return True if the database has any entries."""
        return len(self._commands) > 0
